[master]
node01 ansible_host=192.168.92.136 ansible_user=mohaeid

[workers]
node02 ansible_host=192.168.92.134 ansible_user=mohanad-eid
node03 ansible_host=192.168.92.135 ansible_user=mohanad-eid

[k8s_cluster:children]
master
workers