apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: skyflow-db
type: Opaque
stringData:
  POSTGRES_DB: skyflow_db
  POSTGRES_USER: skyflow_user
  POSTGRES_PASSWORD: SkyFlowPassword123!
