apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skyflow-ingress
  namespace: skyflow-app
spec:
  ingressClassName: nginx
  rules:
  # 1. Rule for Domain Access
  - host: skyflow.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 5000
  # 2. Fallback Rule for Direct IP Access (Dev Environment)
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 5000
